=== nzzdev/Q-election-seats/resources/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "Parlamentswahlen Sitzverteilung",
  "properties": {
    "title": {
      "title": "Titel",
      "type": "string",
      "Q:options": {
        "placeholder": "Der Titel bringt die Kernaussage der Grafik auf den Punkt, zB. 'Die Demokraten sichern sich die Mehrheit'"
      }
    },
    "subtitle": {
      "title": "Untertitel",
      "type": "string",
      "Q:options": {
        "placeholder": "Der Untertitel benennt pr채zise, um welche Wahl es sich handelt."
     }
    },
    "totalSeats": {
      "title": "Total verf체gbare Sitze",
      "type": "number"
    },
    "parties": {
      "title": "Parteien",
      "type": "array",
      "Q:options": {
        "expandable": {
          "itemLabelProperty": "name"
        }
      },
      "items": {
        "type": "object",
        "title": "Partei",
        "properties": {
          "name": {
            "title": "Parteiname oder K체rzel",
            "type": "string"
          },
          "color": {
            "title": "Parteifarbe",
            "type": "object",
            "Q:options": {
              "compact": true,
              "availabilityChecks": [
                {
                  "type": "UserHasRole",
                  "role": "expert-election-seats"
                }
              ]
            },
            "properties": {
              "colorCode": {
                "title": "Farbcode",
                "type": "string",
                "Q:type": "color"
              },
              "classAttribute": {
                "title": "CSS Klassenname",
                "type": "string",
                "Q:options": {
                  "placeholder": "s-viz-color-party-..."
                }
              }
            }
          },
          "seats": {
            "title": "Anzahl Sitze",
            "type": "number"
          },
          "previous": {
            "title": "Anzahl Sitze vergangene Wahl",
            "type": "number",
            "Q:options": {
              "placeholder": "Die Ver채nderung von der vergangenen zu aktuellen Wahl wird dann automatisch berechnet."
            }
          }
        },
        "required": [
          "name"
        ]
      }
    },
    "notes": {
      "title": "Anmerkungen",
      "type": "string"
    },
    "sources": {
      "title": "Quelle(n)",
      "type": "array",
      "items": {
        "type": "object",
        "title": "Quelle",
        "properties": {
          "text": {
            "title": "Quelle",
            "type": "string"
          },
          "link": {
            "Q:type": "link",
            "title": "Link",
            "type": "object",
            "properties": {
              "url": {
                "title": "Link",
                "type": "string",
                "Q:options": {
                  "placeholder": "Direktlink zur Quelle, http://..."
                }
              },
              "isValid": {
                "type": "boolean"
              }    
            }
          }
        },
        "required": ["text"]
      }
    },
    "options": {
      "title": "Optionen",
      "type": "object",
      "Q:options": {
        "availabilityChecks": [
          {
            "type": "UserHasRole",
            "role": "expert-election-seats"
          }
        ]
      },
      "properties": {
        "hideUpdatedDate": {
          "title": "Aktualisierungsdatum ausblenden",
          "type": "boolean",
          "default": false
        }
      }
    }
  },
  "required": [
    "title", "totalSeats"
  ]
}

=== nzzdev/Q-election-seats/resources/fixtures/data/results-color-classes-no-vacancy.json
{
  "title": "FIXTURE: results - color classes - no vacant seats",
  "sources": [
    {
      "text": "NZZ",
      "link": {
        "url": "www.nzz.ch",
        "isValid": true
      }
    }
  ],
  "subtitle": "Möglichkeit zusätzliche Informationen als Untertitel zu erfassen",
  "notes": "Jemand musste Josef K. verleumdet haben, denn ohne dass er 'etwas Böses getan hätte, wurde er eines Morgens verhaftet.",
  "totalSeats": 200,
  "parties": [
    {
      "color": {
        "colorCode": "#004e76",
        "classAttribute": "s-viz-color-party-svp-5"
      },
      "name": "Verfassungsdemokraten",
      "seats": 55
    },
    {
      "color": {
        "classAttribute": "s-viz-color-party-default-5"
      },
      "name": "Kommunistische Partei",
      "seats": 12
    },
    {
      "color": {
        "colorCode": "#6cb8de",
        "classAttribute": "s-viz-color-party-sp-5"
      },
      "name": "Sozialdemokraten",
      "seats": 2
    },
    {
      "color": {
        "classAttribute": "s-viz-color-party-fdp-5"
      },
      "name": "Liberaldemokraten",
      "seats": 111,
      "previous": 212
    },
    {
      "color": {
        "colorCode": "#85b84f"
      },
      "name": "Erneuerung Japans",
      "seats": 0,
      "previous": 0
    },
    {
      "color": {
        "classAttribute": "s-viz-color-party-glp-5"
      },
      "name": "Erfundene Partei mit langem Namen",
      "seats": 20,
      "previous": 12
    }
  ]
}

=== nzzdev/Q-election-seats/resources/fixtures/data/results-partly-previous.json
{
  "title": "FIXTURE: results - partly previous",
  "sources": [
    {
      "text": "NZZ",
      "link": {
        "url": "www.nzz.ch",
        "isValid": true
      }
    }
  ],
  "subtitle": "Möglichkeit zusätzliche Informationen als Untertitel zu erfassen",
  "notes": "Jemand musste Josef K. verleumdet haben, denn ohne dass er 'etwas Böses getan hätte, wurde er eines Morgens verhaftet.",
  "totalSeats": 200,
  "parties": [
    {
      "color": {
        "colorCode": "#004e76"
      },
      "name": "Verfassungsdemokraten",
      "seats": 55
    },
    {
      "color": {
        "colorCode": "#0084c7"
      },
      "name": "Kommunistische Partei",
      "seats": 12
    },
    {
      "color": {
        "colorCode": "#6cb8de"
      },
      "name": "Sozialdemokraten",
      "seats": 2
    },
    {
      "color": {
        "colorCode": "#d3574a"
      },
      "name": "Liberaldemokraten",
      "seats": 111,
      "previous": 212
    },
    {
      "color": {
        "colorCode": "#85b84f"
      },
      "name": "Erneuerung Japans",
      "seats": 0,
      "previous": 12
    },
    {
      "color": {
        "colorCode": "#780f03"
      },
      "name": "Erfundene Partei mit langem Namen",
      "seats": 18,
      "previous": 12
    }
  ]
}

=== nzzdev/Q-election-seats/resources/fixtures/data/no-results-only-previous.json
{
  "title": "FIXTURE: no results - only previous",
  "sources": [
    {
      "text": "NZZ",
      "link": {
        "url": "www.nzz.ch",
        "isValid": true
      }
    }
  ],
  "subtitle": "Möglichkeit zusätzliche Informationen als Untertitel zu erfassen",
  "notes": "Jemand musste Josef K. verleumdet haben, denn ohne dass er 'etwas Böses getan hätte, wurde er eines Morgens verhaftet.",
  "totalSeats": 200,
  "parties": [
    {
      "color": {
        "colorCode": "#004e76"
      },
      "name": "Verfassungsdemokraten",
      "previous": 55
    },
    {
      "color": {
        "colorCode": "#0084c7"
      },
      "name": "Kommunistische Partei",
      "previous": 12
    },
    {
      "color": {
        "colorCode": "#6cb8de"
      },
      "name": "Sozialdemokraten",
      "previous": 2
    },
    {
      "color": {
        "colorCode": "#d3574a"
      },
      "name": "Liberaldemokraten",
      "previous": 120
    },{
      "color": {
        "colorCode": "#85b84f"
      },
      "name": "Erneuerung Japans",
      "previous": 11
    }
  ]
}
